import { Inter } from 'next/font/google'

import ResponsiveAppBar from '@/components/ResponsiveAppBar'
import './globals.css'
import { NextAuthProvider } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Burno',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ResponsiveAppBar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
